version: '3'
services:
  api:
    build: ./back-end
    restart: on-failure
    container_name: api
    image: rayanbak257/api:latest
    ports:
      - "5000:5000"
    volumes:
      - ./:/api
    labels:
      kompose.service.type: LoadBalancer
  front-end:
    build: ./front-end
    restart: on-failure
    container_name: front-end
    image: rayanbak257/front-end:latest
    ports:
      - "2000:2000"
    volumes:
      - ./:/app
    depends_on:
      - api
    labels:
      kompose.service.type: LoadBalancer