apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  containers:
  - image: rayanbak257/api:latest
    name: api
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    resources: {}
    volumeMounts:
    - mountPath: /api
      name: api-claim0
  restartPolicy: OnFailure
  volumes:
  - name: api-claim0
    persistentVolumeClaim:
      claimName: api-claim0
status: {}
